outuntreated: "/path/to/untreated_fits"
outtreated: "/path/to/treated_fits"

expressiondata: "expression_data.csv"
parameterfile: "parameter_bounds_k_strict.csv"
nocorestreatedfit: 32
norepstreatedfithigh: 1000
norepstreatedfitlow: 1000
norepsfinal: 100

optimmethod: [lbfgsb,lm,nmkb,gensa]
gensatimehigh: 1000
gensatimelow: 200
fnscalehigh: 1e6
factrhigh: 1e2
maxithigh: 20000
fnscalelow: 1
factrlow: 1e7
maxitlow: 1000